#!/usr/bin/env python3
"""Report which Y markers a capture panel actually targets.

Why this exists
---------------
Autosomal coverage says nothing about whether a *particular* site was
interrogated. On a targeted-capture library the depth at an off-panel position
is whatever off-target carryover happens to deliver -- usually nothing -- so a
sample with 3x autosomal coverage can still have zero reads at the one
transversion a test turns on. Panel membership is therefore a power fact that
belongs in a pre-registration, decided before any read is looked at.

Matching is done twice, because either alone is wrong:

* **by name** -- panels that carry ISOGG marker names catch the common case,
  but miss any site listed under a synonym or an autogenerated ``snp_<c>_<pos>``
  identifier;
* **by position** -- authoritative, but the panel is usually in GRCh37 while our
  marker index is GRCh38, so it needs a liftover.

Rather than depend on a ``liftOver`` binary, the GRCh38->GRCh37 chain file is
parsed directly (only the blocks for the requested chromosome). A marker that
falls in no chain block is reported ``unmapped`` rather than silently dropped --
an unmappable site is a finding, not a blank.

Panel format is EIGENSTRAT ``.snp``: ``id chrom genpos physpos ref alt``, with
chrY conventionally numbered 24.

Example
-------
    annotate/panel_membership.py \\
        --panel /mnt/MyGenome/Genos/FuQ/51.2.2M.snp \\
        --markers markers/L166_defining.txt markers/backbone_control.txt \\
        --chain /mnt/GenomicData/OpenSNP/puller/hg38ToHg19.over.chain
"""
from __future__ import annotations

import argparse
import gzip
import sys

DEFAULT_INDEX = "resources/marker_index.tsv.gz"


def _open(path: str):
    return gzip.open(path, "rt") if path.endswith(".gz") else open(path)


def load_marker_index(path: str) -> dict[str, dict]:
    out: dict[str, dict] = {}
    with _open(path) as fh:
        hdr = fh.readline().rstrip("\n").split("\t")
        for ln in fh:
            f = ln.rstrip("\n").split("\t")
            if len(f) < len(hdr):
                continue
            r = dict(zip(hdr, f))
            out[r["name"]] = r
    return out


def load_marker_names(paths: list[str]) -> list[str]:
    names: list[str] = []
    seen: set[str] = set()
    for p in paths:
        with open(p) as fh:
            for ln in fh:
                ln = ln.split("#", 1)[0].strip()
                if ln and ln not in seen:
                    seen.add(ln)
                    names.append(ln)
    return names


def load_chain(path: str, chrom: str) -> list[tuple[int, int, int]]:
    """Return (src_start, src_end, delta) blocks mapping source -> target.

    Only same-strand ('+' target) blocks for `chrom` are kept. Inverted blocks
    are skipped: a marker landing in one is reported unmapped rather than given
    a coordinate this simple offset model would get wrong.
    """
    blocks: list[tuple[int, int, int]] = []
    with _open(path) as fh:
        keep = False
        s = t = 0
        for ln in fh:
            ln = ln.strip()
            if ln.startswith("chain"):
                f = ln.split()
                # chain score tName tSize tStrand tStart tEnd qName qSize
                #       qStrand qStart qEnd id
                keep = (f[2] == chrom and f[7] == chrom and f[9] == "+")
                if keep:
                    s, t = int(f[5]), int(f[10])
                continue
            if not keep or not ln:
                continue
            f = ln.split()
            size = int(f[0])
            blocks.append((s, s + size, t - s))
            if len(f) >= 3:
                s += size + int(f[1])
                t += size + int(f[2])
            else:
                keep = False
    blocks.sort()
    return blocks


def lift(pos0: int, blocks: list[tuple[int, int, int]]) -> int | None:
    """Lift a 0-based source coordinate; None if it falls in no block."""
    lo, hi = 0, len(blocks) - 1
    while lo <= hi:
        mid = (lo + hi) // 2
        s, e, d = blocks[mid]
        if pos0 < s:
            hi = mid - 1
        elif pos0 >= e:
            lo = mid + 1
        else:
            return pos0 + d
    return None


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--panel", required=True,
                    help="EIGENSTRAT .snp panel definition")
    ap.add_argument("--markers", required=True, nargs="+",
                    help="one or more marker-name lists (# comments allowed)")
    ap.add_argument("--index", default=DEFAULT_INDEX,
                    help=f"marker coordinate index (default {DEFAULT_INDEX})")
    ap.add_argument("--chain", default=None,
                    help="GRCh38->GRCh37 chain; omit to match by name only")
    ap.add_argument("--chrom", default="chrY")
    ap.add_argument("--panel-chrom", default="24",
                    help="how the panel labels this chromosome (default 24)")
    ap.add_argument("--out", default="-")
    args = ap.parse_args()

    index = load_marker_index(args.index)
    names = load_marker_names(args.markers)

    missing = [n for n in names if n not in index]
    if missing:
        print(f"# not in {args.index}: {','.join(missing)}", file=sys.stderr)

    by_name: dict[str, tuple[int, str, str]] = {}
    by_pos: dict[int, tuple[str, str, str]] = {}
    with _open(args.panel) as fh:
        for ln in fh:
            f = ln.split()
            if len(f) < 6 or f[1] != args.panel_chrom:
                continue
            pos = int(f[3])
            by_name[f[0]] = (pos, f[4], f[5])
            by_pos[pos] = (f[0], f[4], f[5])

    blocks = load_chain(args.chain, args.chrom) if args.chain else []
    if args.chain and not blocks:
        sys.exit(f"no same-strand {args.chrom} blocks in {args.chain}")

    out = sys.stdout if args.out == "-" else open(args.out, "w")
    cols = ["marker", "chrom", "pos_src", "pos_panel", "on_panel",
            "matched_by", "panel_id", "panel_alleles", "marker_alleles",
            "alleles_agree", "isogg", "yfull_node"]
    print("\t".join(cols), file=out)

    n_on = 0
    for n in names:
        r = index.get(n)
        if r is None:
            print("\t".join([n, ".", ".", ".", "unknown", "not_in_index",
                             ".", ".", ".", ".", ".", "."]), file=out)
            continue
        pos_src = int(r["pos"])
        m_all = f"{r['anc']}/{r['der']}"

        lifted = lift(pos_src - 1, blocks) + 1 if blocks else None
        hit_pos = by_pos.get(lifted) if lifted is not None else None
        hit_name = by_name.get(n)

        if hit_pos:
            matched, pid, p_all = "position", hit_pos[0], f"{hit_pos[1]}/{hit_pos[2]}"
            ppos = str(lifted)
        elif hit_name:
            matched, pid, p_all = "name", n, f"{hit_name[1]}/{hit_name[2]}"
            ppos = str(hit_name[0])
        else:
            matched = "none" if lifted is not None or not blocks else "none"
            pid = p_all = "."
            ppos = str(lifted) if lifted is not None else "unmapped"

        on = "yes" if (hit_pos or hit_name) else "no"
        n_on += on == "yes"
        agree = "."
        if on == "yes":
            agree = "yes" if set(p_all.split("/")) == set(m_all.split("/")) else "NO"

        print("\t".join([n, r["chrom"], str(pos_src), ppos, on, matched,
                         pid, p_all, m_all, agree,
                         r.get("isogg", "."), r.get("yfull_node", ".")]),
              file=out)

    print(f"# {n_on}/{len(names)} markers on panel", file=sys.stderr)
    if out is not sys.stdout:
        out.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
